#!/bin/bash
echo "Helping..."
echo ""
echo ""

echo "📚 CCPM - Claude Code Project Manager"
echo "====================================="
echo ""
echo "CCPM is an Agent Skill, not a slash-command pack. There are no /pm:*"
echo "commands — just say what you want and the skill activates."
echo ""
echo "🎯 Quick Start Workflow"
echo "  1. \"write a PRD for <name>\"           - Guided brainstorming -> PRD"
echo "  2. \"parse the <name> PRD\"             - PRD -> technical epic"
echo "  3. \"break down the <name> epic\"       - Epic -> task files"
echo "  4. \"sync the <name> epic to GitHub\"   - Tasks -> GitHub issues"
echo "  5. \"start working on issue <num>\"     - Launch parallel agents"
echo ""
echo "📄 Planning (references/plan.md)"
echo "  \"write a PRD for <name>\"       - Launch brainstorming for a new requirement"
echo "  \"parse the <name> PRD\"         - Convert PRD to implementation epic"
echo "  \"edit the <name> PRD\"          - Targeted edits, frontmatter preserved"
echo ""
echo "📚 Structuring (references/structure.md)"
echo "  \"break down the <name> epic\"   - Decompose epic into numbered task files"
echo ""
echo "🔗 Syncing (references/sync.md)"
echo "  \"sync the <name> epic to GitHub\" - Create epic + task issues, set up worktree"
echo "  \"sync issue <num>\"               - Post progress as an issue comment"
echo "  \"close issue <num>\"             - Close locally and on GitHub"
echo "  \"merge the <name> epic\"         - Test, merge, clean up the worktree"
echo "  \"found a bug in issue <num>\"    - File a linked bug issue"
echo ""
echo "⚡ Executing (references/execute.md)"
echo "  \"start working on issue <num>\"  - Analyze streams, launch parallel agents"
echo "  \"analyze issue <num>\"           - Parallel work stream analysis only"
echo ""
echo "📊 Tracking — these run as scripts (references/track.md)"
echo "  \"what's our status\"        -> status.sh        Overall project dashboard"
echo "  \"standup\"                 -> standup.sh       Daily standup report"
echo "  \"what's next\"             -> next.sh          Next priority tasks"
echo "  \"what's blocked\"          -> blocked.sh       Blocked tasks"
echo "  \"what's in progress\"      -> in-progress.sh   Work in progress"
echo "  \"list the epics\"          -> epic-list.sh     All epics"
echo "  \"show the <name> epic\"    -> epic-show.sh     Epic and its tasks"
echo "  \"status of <name> epic\"   -> epic-status.sh   Epic progress"
echo "  \"list the PRDs\"           -> prd-list.sh      All PRDs"
echo "  \"PRD status\"              -> prd-status.sh    PRD implementation status"
echo "  \"search for <query>\"      -> search.sh        Search across all content"
echo "  \"validate the project\"    -> validate.sh      Check system integrity"
echo ""
echo "⚙️  Setup"
echo "  init.sh - Install dependencies and configure GitHub labels"
echo "  help.sh - Show this help message"
echo ""
echo "💡 Tips"
echo "  • Ask \"what's next\" to find available work"
echo "  • Ask \"what's our status\" for a quick overview"
echo "  • Full flow: PRD -> epic -> tasks -> GitHub issues -> parallel agents"
echo "  • Read references/conventions.md for paths and frontmatter schemas"
echo "  • View README.md for complete documentation"

exit 0
